# apiVersion: v1
# kind: Service
# metadata:
#   name: diaryToy
#   namespace: diaryToy
# spec:
#   type: NodePort
#   selector:
#     app: diary-toy
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8088
#     nodePort: 30000

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wndudwns
  name: wndudwns
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: wndudwns
  type: NodePort
status:
  loadBalancer: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wndudwns
  name: wndudwns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wndudwns
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wndudwns
    spec:
      containers:
      - image: wndudwns0028/diary
        name: diary
        resources: {}
status: {}
